# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_core.utils.ipynb (unless otherwise specified).

__all__ = ['multiply']

# Cell
def multiply(a,b):
    """
    multiply values

    Args:

        a ([float/int]): any value

        b ([float/int]): any value
    """
    return a*b