# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"multiply": "01_core.utils.ipynb"}

modules = ["utils/math.py"]

doc_url = "https://pandya6988.github.io/prac/"

git_url = "https://github.com/pandya6988/prac/tree/master/"

def custom_doc_links(name): return None
